image: 
  height: 720
  width: 557
  #path: "./data/Map_WO_obstacle.png"
  path: "./data/Map_WITH_obstacle.png"

color: 
  obstacle: (0, 0, 0, 255) 
  obstacle-hex: "#000000"
  border-hex: "#000000"
  border: (0, 0, 0, 255) 
  target: (64, 166, 74, 225)
  target-hex: "#40a64a"

parameters:
  alignment: 0.5
  cohesion: 0.3
  separation: 0.8
  
people:
   num: 500

security:
   percentage: 0
   # can be 0.01 or 0.02 or 0.03 or 0.04 or 0.05






