image: 
  height: 720
  width: 557
  path: "./data/Map_WO_obstacle.jpg"
  #path: "./data/Map_WITH_obstacle.jpg"

color: 
  obstacle: (0, 0, 0, 255) 
  border: (0, 0, 0, 255) 
  target: (125, 197, 53, 255)
  target-hex: "#7dc535"

parameters:
  alignment: 0.5
  cohesion: 0.5
  separation: 0.5
  
people:
   num: 10

security:
   nums: 10






