image: 
  height: 720
  width: 557
  path: "./data/Map_WO_obstacle.jpg"
  #path: "./data/Map_WITH_obstacle.jpg"

color: 
  obstacle: (0, 0, 0, 255) 
  border: (0, 0, 0, 255) 
  target: (125, 197, 53, 255)

people:
   num: 100






